fix(tests): Fix test failures due to unflagged strip-types
Update tests to handle `--experimental-strip-types` being unflagged by default in newer Node.js versions. See https://nodejs.org/en/blog/release/v22.18.0. This was causing test failures in CI similar to the following:

```
Expected substring: "jest.config.ts(2,25): error TS2322: Type 'string' is not assignable to type 'number'."
Received string:    "● Validation Error:·
  Option \"testTimeout\" must be of type:
    number
  but instead received:
    string·
  Example:
  {
    \"testTimeout\": 5000
  }·
  Configuration Documentation:
  https://jestjs.io/docs/configuration
"

    at Object.toMatch (e2e/__tests__/tsIntegration.test.ts:573:20)
```

and

```
    Expected substring: "PASS __tests__/mytest.alpha.js"
    Received string:    "Error: Jest: Failed to parse the TypeScript config file /tmp/typescript-config-file/alpha.config.ts
      Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/typescript-config-file/common' imported from /tmp/typescript-config-file/alpha.config.ts
        at readConfigFileAndSetRootDir (/home/runner/work/jest/jest/packages/jest-config/build/index.js:2269:13)
        at async readInitialOptions (/home/runner/work/jest/jest/packages/jest-config/build/index.js:1147:13)
        at async readConfig (/home/runner/work/jest/jest/packages/jest-config/build/index.js:918:7)
        at async Promise.all (index 0)
        at async readConfigs (/home/runner/work/jest/jest/packages/jest-config/build/index.js:1184:27)
        at async runCLI (/home/runner/work/jest/jest/packages/jest-core/build/index.js:1393:7)
        at async Object.run (/home/runner/work/jest/jest/packages/jest-cli/build/index.js:656:9)"

      102 |   );
      103 |
    > 104 |   expect(stderr).toContain('PASS __tests__/mytest.alpha.js');
          |                  ^
      105 |   expect(stderr).toContain('PASS __tests__/mytest.beta.js');
      106 |   expect(stderr).toContain('PASS __tests__/mytest.common.js');
      107 |   expect(stderr.replace('PASS __tests__/mytest.common.js', '')).toContain(

      at Object.toContain (e2e/__tests__/typescriptConfigFile.test.ts:104:18)
```